# Generated by Django 3.1 on 2021-04-19 06:37

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', user.models.MyUserManager()),
            ],
        ),
    ]
